[05-25-2022 11:48:32 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-7' coro=<start() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\main.py:36> exception=ValueError("could not convert string to float: 'fedg'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\main.py", line 38, in start
    float("fedg")
ValueError: could not convert string to float: 'fedg'
[05-25-2022 11:48:45 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Loop._loop() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py:140> exception=AttributeError("'AutoShardedInteractionBot' object has no attribute 'db'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 186, in _loop
    raise exc
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 157, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\fixin\PycharmProjects\GambleBot\cogs\credit.py", line 134, in check_bills
    async with self.bot.db.execute("""CREATE TABLE IF NOT EXISTS credit(
AttributeError: 'AutoShardedInteractionBot' object has no attribute 'db'
[05-25-2022 11:48:45 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Loop._loop() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py:140> exception=AttributeError("'AutoShardedInteractionBot' object has no attribute 'db'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 186, in _loop
    raise exc
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 157, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\fixin\PycharmProjects\GambleBot\cogs\shop.py", line 91, in security_loop
    async with self.bot.db.execute("""CREATE TABLE IF NOT EXISTS security(
AttributeError: 'AutoShardedInteractionBot' object has no attribute 'db'
[05-25-2022 11:48:45 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Loop._loop() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py:140> exception=AttributeError("'AutoShardedInteractionBot' object has no attribute 'db'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 186, in _loop
    raise exc
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 157, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\fixin\PycharmProjects\GambleBot\cogs\drugs.py", line 158, in supplies_loop
    async with self.bot.db.execute("""CREATE TABLE IF NOT EXISTS business(
AttributeError: 'AutoShardedInteractionBot' object has no attribute 'db'
[05-25-2022 11:48:45 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Loop._loop() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py:140> exception=AttributeError("'AutoShardedInteractionBot' object has no attribute 'db'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 186, in _loop
    raise exc
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 157, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\fixin\PycharmProjects\GambleBot\cogs\drugs.py", line 203, in cops_loop
    async with self.bot.db.execute("""CREATE TABLE IF NOT EXISTS business(
AttributeError: 'AutoShardedInteractionBot' object has no attribute 'db'
[05-26-2022 05:07:44 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Loop._loop() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py:140> exception=ValueError("could not convert string to float: 'hjgj'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 186, in _loop
    raise exc
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 157, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\fixin\PycharmProjects\GambleBot\cogs\credit.py", line 133, in check_bills
    float("hjgj")
ValueError: could not convert string to float: 'hjgj'
[05-26-2022 05:10:11 PM] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Loop._loop() done, defined at C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py:140> exception=ValueError("could not convert string to float: 'hjgj'")>
Traceback (most recent call last):
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 186, in _loop
    raise exc
  File "C:\Users\fixin\PycharmProjects\GambleBot\venv\lib\site-packages\disnake\ext\tasks\__init__.py", line 157, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\fixin\PycharmProjects\GambleBot\cogs\credit.py", line 133, in check_bills
    async with self.bot.db.execute("""CREATE TABLE IF NOT EXISTS credit(
ValueError: could not convert string to float: 'hjgj'
